# Generated by Django 3.1.5 on 2021-01-27 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
